---
- name: Haproxy_DR.cfg 
  hosts: all
  tasks:
    - name: Copy haproxy_DR.cfg from /tmp
      copy:
        src: /tmp/haproxy_dr.cfg
        dest: /home/sysop/haproxy.cfg
        remote_src: yes

    - name: Restart haproxy
      systemd:
        name: haproxy
        state: restarted
