---
- name: Move DR_cfg
  hosts: all
  become: yes
  tasks:
    - name: Copy DR_cfg 
      copy:
        src: /tmp/haproxy_dr.cfg
        dest: /etc/haproxy/haproxy.cfg
        remote_src: yes

    - name: Set permissions
      file:
        path: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"

    - name: Restart haproxy
      systemd:
        name: haproxy
        state: restarted
