---
- name: Copy haproxy_DR.cfg and restart haproxy
  hosts: all
  tasks:
    - name: Copy haproxy_DR.cfg
      copy:
        src: /tmp/haproxy
        dest: /home/sysop/haproxy.cfg
      notify: Restart haproxy
      delegate_to: localhost

  handlers:
    - name: Restart haproxy
      systemd:
        name: haproxy
        state: restarted
